# Generated by Django 4.1 on 2022-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbyssRaids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="abyssraids/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Abyss Raid", "Abyss Raid")], max_length=200
                    ),
                ),
                ("comp", models.IntegerField(default=0)),
                ("gates", models.IntegerField(default=0)),
                ("minimum_level", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Abyss Raids",
            },
        ),
        migrations.CreateModel(
            name="LegionRaids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="legionraids/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Legion Raid", "Legion Raid")], max_length=200
                    ),
                ),
                ("comp", models.IntegerField(default=0)),
                ("gates", models.IntegerField(default=0)),
                ("minimum_level", models.IntegerField(default=0)),
                ("minimum_level2", models.IntegerField(default=0)),
                ("minimum_level3", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Legion Raids",
            },
        ),
    ]
