# Generated by Django 4.1 on 2022-08-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abyssraids",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/abyssraids/"
            ),
        ),
        migrations.AlterField(
            model_name="legionraids",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/legionraids/"
            ),
        ),
    ]
