# Generated by Django 4.1 on 2022-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_abyssraids_image_alter_legionraids_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Runs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube", models.URLField(blank=True, null=True)),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="runs/"),
                ),
                (
                    "raid_type",
                    models.CharField(
                        choices=[
                            ("Abyss Raid", "Abyss Raid"),
                            ("Legion Raid", "Legion Raid"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "raid_name",
                    models.CharField(
                        choices=[
                            ("Argos", "Argos"),
                            ("Valtan", "Vykas"),
                            ("Kakul-Saydon", "Kakul-Saydon"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Hard", "Hard"),
                            ("Inferno", "Inferno"),
                        ],
                        max_length=200,
                    ),
                ),
                ("time", models.IntegerField(default=0)),
                ("deathless", models.BooleanField(default=False)),
                ("discord", models.CharField(max_length=200)),
                ("playerOne", models.CharField(max_length=200)),
                ("playerTwo", models.CharField(max_length=200)),
                (
                    "playerThree",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("playerFour", models.CharField(blank=True, max_length=200, null=True)),
                ("playerFive", models.CharField(blank=True, max_length=200, null=True)),
                ("playerSix", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "playerSeven",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "playerEight",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("playerOneLVL", models.IntegerField(default=0)),
                ("playerTwoLVL", models.IntegerField(default=0)),
                (
                    "playerThreeLVL",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "playerFourLVL",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "playerFiveLVL",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("playerSixLVL", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "playerSevenLVL",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "playerEightLVL",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Runs",
            },
        ),
    ]
