# Generated by Django 4.1 on 2022-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_runs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runs",
            name="time",
            field=models.CharField(max_length=10),
        ),
    ]
