# Generated by Django 4.1 on 2022-08-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_runs_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="runs",
            name="averageIlvl",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="runs",
            name="raid_name",
            field=models.CharField(
                choices=[
                    ("Argos", "Argos"),
                    ("Valtan", "Valtan"),
                    ("Vykas", "Vykas"),
                    ("Kakul-Saydon", "Kakul-Saydon"),
                ],
                max_length=200,
            ),
        ),
    ]
