# Generated by Django 4.1 on 2022-08-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_runs_averageilvl_alter_runs_raid_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runs",
            name="averageIlvl",
        ),
    ]
