# Generated by Django 4.1 on 2022-08-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_runs_averageilvl"),
    ]

    operations = [
        migrations.AddField(
            model_name="runs",
            name="averageIlvl",
            field=models.FloatField(default=0),
        ),
    ]
