# Generated by Django 4.1 on 2022-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateTimeField(default="29/08/2022"),
        ),
    ]
