version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: docker-loaruns-db
    environment:
      POSTGRES_USER: persa
      POSTGRES_PASSWORD: loaruns
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build:
      context: .
      dockerfile: ./docker/BackendDockerfile
    container_name: docker-loaruns-backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: persa
      POSTGRES_PASSWORD: loaruns
      POSTGRES_HOST: localhost
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    build:
      context: .
      dockerfile: ./docker/FrontendDockerfile
    container_name: docker-loaruns-frontend
    command: ./docker/frontend_setup.sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - django
